name: Benchmark-Docker

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: docker build . -t benchmark

      - name: Run
        run: docker run benchmark
